# Generated by Django 2.1.2 on 2018-10-16 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20181016_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 16, 11, 57, 17, 415273, tzinfo=utc)),
        ),
    ]
